// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBq7BBozohG-d3xwbXiiQgmpRP4rp8GCE',
    appId: '1:564831401660:web:62084b50fd7f0271eec2b9',
    messagingSenderId: '564831401660',
    projectId: 'chitflow-149ff',
    authDomain: 'chitflow-149ff.firebaseapp.com',
    storageBucket: 'chitflow-149ff.firebasestorage.app',
    measurementId: 'G-EYSL86CGBF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3h7DLDq1Sr09orJDmd70H0EkXqGFPIhs',
    appId: '1:564831401660:ios:d0d2ad172f0c45e8eec2b9',
    messagingSenderId: '564831401660',
    projectId: 'chitflow-149ff',
    storageBucket: 'chitflow-149ff.firebasestorage.app',
    iosBundleId: 'com.chitflow.chitflow',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3h7DLDq1Sr09orJDmd70H0EkXqGFPIhs',
    appId: '1:564831401660:ios:d0d2ad172f0c45e8eec2b9',
    messagingSenderId: '564831401660',
    projectId: 'chitflow-149ff',
    storageBucket: 'chitflow-149ff.firebasestorage.app',
    iosBundleId: 'com.chitflow.chitflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBq7BBozohG-d3xwbXiiQgmpRP4rp8GCE',
    appId: '1:564831401660:web:eca604e403688986eec2b9',
    messagingSenderId: '564831401660',
    projectId: 'chitflow-149ff',
    authDomain: 'chitflow-149ff.firebaseapp.com',
    storageBucket: 'chitflow-149ff.firebasestorage.app',
    measurementId: 'G-NW6WH07S9S',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1hEaRQdHku3-yMuOH4G29SDUlet7d6Oo',
    appId: '1:564831401660:android:f4de32bd9b8d4372eec2b9',
    messagingSenderId: '564831401660',
    projectId: 'chitflow-149ff',
    storageBucket: 'chitflow-149ff.firebasestorage.app',
  );
}
